/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author estudiantes
 */
public class cajero extends javax.swing.JFrame {

    /**
     * Creates new form cajero
     */
    public cajero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        algo = new javax.swing.JButton();
        continuar = new javax.swing.JButton();
        mostrar_opciones = new javax.swing.JLabel();
        obtener_opciones = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        retirar = new javax.swing.JButton();
        depocitar = new javax.swing.JButton();
        transaccion = new javax.swing.JButton();
        algo2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        algo4 = new javax.swing.JLabel();
        algo5 = new javax.swing.JLabel();
        algo6 = new javax.swing.JLabel();
        algo7 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("cajero_pedro_nicolas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 120, 20));

        jLabel2.setText("#32456");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 50, 20));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("borrar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 70, 40));

        uno.setBackground(new java.awt.Color(204, 204, 204));
        uno.setText("1");
        uno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, 40, 40));

        dos.setBackground(new java.awt.Color(204, 204, 204));
        dos.setText("2");
        dos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, 40, 40));

        tres.setBackground(new java.awt.Color(204, 204, 204));
        tres.setText("3");
        tres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 590, 40, 40));

        seis.setBackground(new java.awt.Color(204, 204, 204));
        seis.setText("6");
        seis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        jPanel1.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, 40, 40));

        cinco.setBackground(new java.awt.Color(204, 204, 204));
        cinco.setText("5");
        cinco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 40, 40));

        cuatro.setBackground(new java.awt.Color(204, 204, 204));
        cuatro.setText("4");
        cuatro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, 40, 40));

        siete.setBackground(new java.awt.Color(204, 204, 204));
        siete.setText("7");
        siete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 690, 40, 40));

        ocho.setBackground(new java.awt.Color(204, 204, 204));
        ocho.setText("8");
        ocho.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, 40, 40));

        nueve.setBackground(new java.awt.Color(204, 204, 204));
        nueve.setText("9");
        nueve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 690, 40, 40));

        cero.setBackground(new java.awt.Color(204, 204, 204));
        cero.setText("0");
        cero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });
        jPanel1.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 740, 40, 40));

        algo.setBackground(new java.awt.Color(255, 204, 0));
        algo.setForeground(new java.awt.Color(255, 255, 255));
        algo.setText("algo");
        algo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        jPanel1.add(algo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 60, 40));

        continuar.setBackground(new java.awt.Color(0, 102, 0));
        continuar.setForeground(new java.awt.Color(255, 255, 255));
        continuar.setText("continuar");
        continuar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        jPanel1.add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 690, 90, 40));

        mostrar_opciones.setText("mostrar_opciones");
        mostrar_opciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(mostrar_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 220, 20));

        obtener_opciones.setText("obtener_opciones");
        obtener_opciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(obtener_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 220, 20));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("consultar saldo");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 90, 30));

        retirar.setBackground(new java.awt.Color(204, 204, 204));
        retirar.setText("retirar");
        retirar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(retirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 90, 30));

        depocitar.setBackground(new java.awt.Color(204, 204, 204));
        depocitar.setText("depositar");
        depocitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(depocitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 90, 30));

        transaccion.setBackground(new java.awt.Color(204, 204, 204));
        transaccion.setText("transaccion");
        transaccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(transaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 90, 30));

        algo2.setText("algo2");
        algo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(algo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 220, -1));

        jLabel3.setText("algo3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 220, -1));

        algo4.setText("algo4");
        algo4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(algo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 220, -1));

        algo5.setText("algo5");
        algo5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(algo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 220, -1));

        algo6.setText("algo6");
        algo6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(algo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 220, -1));

        algo7.setText("algo7");
        algo7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(algo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 220, 20));

        Salir.setBackground(new java.awt.Color(255, 102, 51));
        Salir.setText("SALIR");
        Salir.setActionCommand("");
        Salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 80, 30));
        Salir.getAccessibleContext().setAccessibleName("Salir");

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cajero.jpg"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, -1, 938));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seisActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ceroActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton algo;
    private javax.swing.JLabel algo2;
    private javax.swing.JLabel algo4;
    private javax.swing.JLabel algo5;
    private javax.swing.JLabel algo6;
    private javax.swing.JLabel algo7;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton continuar;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton depocitar;
    private javax.swing.JButton dos;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mostrar_opciones;
    private javax.swing.JButton nueve;
    private javax.swing.JLabel obtener_opciones;
    private javax.swing.JButton ocho;
    private javax.swing.JButton retirar;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton transaccion;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
